#cloud-config
package_upgrade: true
write_files:
  - content: |
      Port 49444
      TCPKeepAlives yes
    path: /etc/ssh/sshd_config
    append: true
power_state:
  mode: reboot
  delay: 1
  message: "cleanup reboot"
