#cloud-config
package_upgrade: true
packages:
  - wireguard
write_files:
  - content: |
      net.ipv4.ip_forward=1
    path: /etc/sysctl.d/99-custom.conf
    permissions: '0644'
runcmd:
  - sed -i -e '/^Port/s/^.*$/Port 49444/' /etc/ssh/sshd_config
  - sed -i -e '/^TCPKeepAlive/s/^.*$/TCPKeepAlive yes/' /etc/ssh/sshd_config
  - sed -i -e '/^PrintMotd/s/^.*$/PrintMotd no/' /etc/ssh/sshd_config
power_state:
  mode: reboot
  delay: 1
  message: "cleanup reboot"    
