#!/bin/zsh
#set -x

# "known good defaults", can be modified in CONFIG file

PROJ=pnat
LOCATION=
CONFIG=./config

source ${CONFIG}

# Check if Azure CLI exists

echo -n "checking for Azure CLI.."
az account show -otable 2>&1 >/dev/null
if [ $? -eq 0 ]; then
  echo " found."
else
  echo " doesn't exist or is busted.. Install Azure CLI or check installation (az login'ed?)."
  exit 1
fi

# Advise on location

if [[ -z ${LOCATION} ]]; then
  echo -n "LOCATION parameter in file  ${CONFIG} missing. aborting." && exit 1
else
  echo -n "LOCATION found in ${CONFIG}. Using "
fi
echo "region ${LOCATION}."

# Delete rg's

for COMPONENT in shared source destination; do
  RG=${PROJ}-${COMPONENT}-rg
  date | tee -a ${LOG}
  echo -n "rg ${RG} does"
  if [[ "$(az group exists --name ${RG})" == "true" ]]; then
    echo -n " exist.."
    if [[ "${COMPONENT}" != "shared" || -n "${FORCE}" ]]; then
      echo -n " deleting.."
      az group delete \
        --resource-group ${RG} \
        --yes \
        --only-show-errors \
        >${LOG} 2>&1 || exit 1
    else
      echo " preserved."
    fi
  else
    echo -n "n't exist.."
  fi
done
date | tee -a ${LOG}

# Everything _should_ be gone by the time we get here. "GOOD LUCK."

echo -n "END: " | tee -a ${LOG}
date | tee -a ${LOG}

echo "done."

exit 0
