#cloud-config
package_upgrade: true
packages:
  - wireguard
write_files:
  - content: |
      net.ipv4.ip_forward=1
    path: /etc/sysctl.d/99-custom.conf
    permissions: '0644'
  - content: |
      Port 49444
      TCPKeepAlives yes
    path: /etc/ssh/sshd_config
    append: true
power_state:
  mode: reboot
  delay: 1
  message: "cleanup reboot"
